name: Create lib-ml Pre-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # triggers on something like v1.0.0-pre-1

jobs:
  build-and-publish:
    name: Build & Create GitHub Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code at the tagged commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build tools and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt

      - name: Download NLTK stopwords
        run: python -c "import nltk; nltk.download('stopwords')"

      - name: Build Python package
        run: python -m build --sdist --wheel .

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Pre-release lib-ml ${{ github.ref_name }}
          body: "Automated pre-release of the lib-ml Python package."
          prerelease: true
          files: dist/*
