name: Release lib-ml

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code at tagged commit
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build tools and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build # Install the standard 'build' package
          pip install -r requirements.txt

      - name: Download NLTK stopwords
        run: python -c "import nltk; nltk.download('stopwords')"

      - name: Build Python package
        run: python -m build --sdist --wheel .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
