name: Release lib-ml

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    name: Build and Create Stable Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code at tagged commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build tools and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt

      - name: Download NLTK stopwords
        run: python -c "import nltk; nltk.download('stopwords')"

      - name: Build Python package
        run: python -m build --sdist --wheel .

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release lib-ml ${{ github.ref_name }}
          body: "Stable release of the lib-ml package"
          prerelease: false
          files: dist/*