name: Verify and Release lib-ml

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Trigger workflow on version tags

jobs:
  build-verify-release:
    name: Build, Verify, and Release lib-ml
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Step 3: Install dependencies from requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Download NLTK data explicitly
      - name: Download NLTK stopwords
        run: python -m nltk.downloader stopwords

      # Step 5: Build package
      - name: Build package
        run: python -m build --verbose

      # Step 6: Publish distribution to GitHub Packages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libml-dist
          path: dist/